version: '3.4'

services:
  node:
    image: feeder:master
    logging:
      driver: none
    ports:
      - "26656-26657:26656-26657"
      - "9090:9090"
      - "1317:1317"
    expose:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"
    entrypoint: ["sh", "./node.sh"]

  oracle:
    image: feeder:master
    environment:
      FEEDER_CONFIG: "{chain_id: 'testing', grpc_endpoint: 'node:9090', tendermint_websocket_endpoint: 'ws://node:26657/websocket', validator: nibivaloper1hrdy4frcgp6xhdcedu66unzvrx2v6yg80a5e9c, feeder: nibi1hrdy4frcgp6xhdcedu66unzvrx2v6yg8xx6z39, cache: mem, key_ring: 8567b2363d290b8604dade49409ecd5a14e91eb08d16489796513b76c02628aa, chain_to_exchange_symbols: {binance: {'ubtc:unusd': BTCUSDT, 'ueth:unusd': ETHUSDT, 'uusdc:unusd': USDCUSDT}, bitfinex: {'ubtc:unusd': tBTCUSD, 'ueth:unusd': tETHUSD, 'uusd:unusd': tUSTUSD}}}"
    entrypoint: ["sh", "./oracle.sh"]
