name: EVM e2e tests

on:
  pull_request:
    paths: ["**.go", "**.proto", "go.mod", "go.sum", "**go.mod", "**go.sum", "contrib/docker/*", "**.js", "**.json"]

# Allow concurrent runs on main/release branches but isolates other branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true

      # Use GitHub actions output paramters to get go paths. For more info, see
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - name: "Set output variables for go cache"
        id: go-cache-paths
        run: |
          echo "go-build-cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod-cache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: "Go build cache"
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build-cache }}
          key: go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: "Go mod cache"
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod-cache }}
          key: go-mod-cache-${{ hashFiles('**/go.sum') }}

      - name: "Install just"
        # casey/just: https://just.systems/man/en/chapter_6.html
        # taiki-e/install-action: https://github.com/taiki-e/install-action
        uses: taiki-e/install-action@just

      - name: "Build the nibid binary"
        run: |
          just install

      - name: Setup NodeJS with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"
          cache: "yarn"

      - name: Install node_modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "tests/evm"

      - name: "Launch localnet"
        run: |
          just localnet --no-build &
          sleep 6

      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test
          working-directory: "tests/evm"
        env:
          JSON_RPC_ENDPOINT: http://127.0.0.1:8545
          MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
