---
name: CosmWasm e2e contract tests

on:
  # On normal PRs or when workflow goreleaser finishes, as it gets the last release tag.
  pull_request:

# Allow concurrent runs on main/release branches but isolates other branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: "Install just"
        # casey/just: https://just.systems/man/en/chapter_6.html
        # taiki-e/install-action: https://github.com/taiki-e/install-action
        uses: taiki-e/install-action@just

      - name: "Build the nibid binary + Run localnet"
        run: |
          just install
          just localnet

      - name: run e2e tests
        run: |
          sh ./contrib/scripts/e2e/deploy-wasm.sh
