---
name: CosmWasm deployment contract CI

on:
  pull_request:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Get Latest Release
       uses: pozetroninc/github-action-get-latest-release@v0.6.0
       with:
         repository: ${{ github.repository }}
