name: goreleaser

on:
  push:
    tags:
      - "*"
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Login to GHCR container register
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tagged image
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          file: contrib/docker/goreleaser.Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/nibiru:${{ steps.get_version.outputs.version-without-v }}
      
      - name: Build and push latest image
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          file: contrib/docker/goreleaser.Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/nibiru:latest