name: Integration tests on master

# Runs on master merge only.
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'integration-test'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
  integration-tests:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all tests.
        run: make test-integration