name: Integration tests on master

# Runs on master merge only.
on:
  pull_request_review:
    types: [ submitted ]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event context
        id: github_event
        run: echo '${{ toJSON(github.event) }}'
  integration-tests:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Run all tests.
        run: make test-integration