name: Proto Generation

on:
  pull_request:
    paths: ["**.proto", "**protocgen-any.sh", "**protocgen.sh"]

jobs:
  proto-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Login to GHCR container register
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/nibiruchain/cosmossdk-proto:v0.1.0

      - name: Generate proto code
        run: make proto-gen
