name: Run short simulations

on:
  pull_request:

jobs:
  install-runsim:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0

  test-sim-nondeterminism:
    runs-on: ubuntu-18.04
    needs: [install-runsim]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-nondeterminism
        run: |
          make test-sim-nondeterminism
